---
title: "README"
author: "Eric Graves"
date: "July 10, 2017"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rulefit)
data(titanic, package="binnr")
```

## Installation

```{r install, eval=FALSE}
devtools::install_git("https://GravesEE@gitlab.ins.risk.regn.net/minneapolis-r-packages/rulefit.git")
```

## Usage

### Training

```{r train, warning=FALSE}

# mod <- gbm(Survived~., data=titanic, distribution="bernoulli",
#   interaction.depth=3, shrinkage=0.1)

mod <- gbm.fit(titanic[-1], titanic$Survived, distribution="bernoulli",
  interaction.depth=3, shrinkage=0.1, verbose = FALSE)

rf <- RuleFit(mod, titanic[-1])

print(rf)
```

### Predicting

```{r predict, warning=FALSE}

p_min <- predict(rf, titanic[-1], s="lambda.min")
p_1se <- predict(rf, titanic[-1], s="lambda.1se")

roc_min <- pROC::roc(titanic$Survived, -p_min)
roc_1se <- pROC::roc(titanic$Survived, -p_1se)

plot(roc_min)
par(new=TRUE)
plot(roc_1se, col="red")

```


### Predicting on New Data

```{r new-data}
v <- rf$gbm_model$var.names
p_sample <- predict(rf, newdata=head(titanic)[v], s="lambda.min")
p_sample
```


### Keeping K-Fold Predictions

```{r keep-k-fold, warning=FALSE}

rf2 <- RuleFit(mod, titanic[-1], keep=TRUE)
dev <- predict(rf2, titanic[-1], s="lambda.min")
val <- rf2$glmnet_mod$fit.preval[, which.min(rf2$glmnet_mod$cvm)]

roc_dev <- pROC::roc(titanic$Survived, -dev)
roc_val <- pROC::roc(titanic$Survived, -val)

plot(roc_dev)
par(new=TRUE)
plot(roc_val, col="red")
```

### Exporting SAS Code

```{r, export-to-sas}
code <- rulefit_to_sas(rf, pfx="mod1")
writeLines(code, "rule_fit_model.sas")
```

Code sample of first and last 6 lines:

```{r, export-to-sas2, echo=FALSE, results='hold'}
cat(head(readLines("rule_fit_model.sas")), sep="\n")
cat("\n...\n\n")
cat(tail(readLines("rule_fit_model.sas")), sep="\n")
```

